spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fin_core_local?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: your-local-user
    password: your-local-password
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
